### PR TITLE
Add Travis

### PR DESCRIPTION
**Pull request by hugomd**
This PR adds a `.travis.yml`, so that tests run automatically 🎉

### CODE REVIEW

**Comment by pseudo-su** [comment]
Stranger danger! Don't trust this man 😱

**Comment by hugomd** [comment]
@psuedoSudo ❗️❓ I'll have you know, I'm a respected member of the Open Source community!

**Comment by hugomd** [comment]
Please merge 🙏

**Comment by halbrd** [comment]
Still have some unit tests to write but I guess there's no reason not to

**Pull request merged**
